blog/urls.py
from django.urls import path

from blog.views import BlogListView, BlogDetailView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from blog import urls
import blog
from users import urls
import users
from mail_messages import urls
import mail_messages

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(mail_messages.urls, namespace='mail_messages')),
    path('users/', include(users.urls, namespace='users')),
    path('blog/', include(blog.urls, namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mail_messages/urls.py
from django.urls import path
from .views import (
    ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView,
    MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView,
    MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView,
    MailingAttemptListView, MailingAttemptDetailView, MailingAttemptCreateView, MailingAttemptUpdateView,
    MailingAttemptDeleteView, MainView,
)

app_name = "mail_messages"

urlpatterns = [
    path('', (MainView.as_view()), name='main'),

    # КЛИЕНТ
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('clients/create/', ClientCreateView.as_view(), name='client_create'),
    path('clients/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('clients/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),

    # СООБЩЕНИЕ
    path('messages/', MessageListView.as_view(), name='message_list'),
    path('messages/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('messages/create/', MessageCreateView.as_view(), name='message_create'),
    path('messages/<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('messages/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),

    # РАССЫЛКА
    path('mailing/', MailingListView.as_view(), name='mailing_list'),
    path('mailing/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing/<int:pk>/update/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),

    # ПОПЫТКА РАССЫЛКИ
    path('mailing-attempt/', MailingAttemptListView.as_view(), name='mailing_attempt_list'),
    path('mailing-attempt/<int:pk>/', MailingAttemptDetailView.as_view(), name='mailing_attempt_detail'),
    path('mailing-attempt/create/', MailingAttemptCreateView.as_view(), name='mailing_attempt_create'),
    path('mailing-attempt/<int:pk>/update/', MailingAttemptUpdateView.as_view(), name='mailing_attempt_update'),
    path('mailing-attempt/<int:pk>/delete/', MailingAttemptDeleteView.as_view(), name='mailing_attempt_delete'),
]

mail_messages/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


# Клиент
class Client(models.Model):
    email = models.EmailField(unique=True, verbose_name='почта')
    full_name = models.CharField(max_length=255, verbose_name='ФИО')
    comment = models.TextField(**NULLABLE, verbose_name='комментарий')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE,
                              verbose_name='владелец',
                              related_name='clients'
                              )

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


# Сообщение
class Message(models.Model):
    subject = models.CharField(max_length=255, verbose_name='тема письма')
    body = models.TextField(verbose_name='тело письма')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE,
                              verbose_name='владелец',
                              related_name='messages'
                              )

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'соббщение'
        verbose_name_plural = 'сообщения'


# Рассылка
class Mailing(models.Model):
    PERIODICITY_CHOICES = [
        ('daily', 'Раз в день'),
        ('weekly', 'Раз в неделю'),
        ('monthly', 'Раз в месяц'),
    ]

    STATUS_CHOICES = [
        ('created', 'Создана'),
        ('started', 'Запущена'),
        ('completed', 'Завершена'),
    ]

    title = models.CharField(max_length=100, default='Без названия', verbose_name='Название рассылки')
    start_datetime = models.DateTimeField(verbose_name='Дата и время первой рассылки')
    periodicity = models.CharField(max_length=10, choices=PERIODICITY_CHOICES, verbose_name='Периодичность рассылки')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='created', verbose_name='Статус рассылки')
    message = models.OneToOneField(Message, on_delete=models.CASCADE, verbose_name='Сообщение')
    clients = models.ManyToManyField(Client, verbose_name='Клиенты')
    is_active = models.BooleanField(default=True, verbose_name='активность рассылки')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE,
                              verbose_name='владелец',
                              related_name='mailings'
                              )

    def __str__(self):
        return f"{self.title} (ID: {self.id}) - {self.status}"

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

        permissions = [
            ("can_disable_mailing", "Can disable mailing"),
        ]


# Попытка рассылки
class MailingAttempt(models.Model):
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='рассылка')
    attempt_datetime = models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней рассылки')
    status = models.CharField(max_length=10, choices=[('success', 'Успешно'), ('failed', 'Неуспешно')], verbose_name='статус попытки')
    server_response = models.TextField(verbose_name='ответ почтового сервиса', **NULLABLE)

    def __str__(self):
        return f"Attempt for mailing {self.mailing.id} - {self.status}"

    class Meta:
        verbose_name = 'попытка рассылки'
        verbose_name_plural = 'попытки рассылки'

mail_messages/forms.py
from django import forms
from .models import Client, Message, Mailing, MailingAttempt


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['email', 'full_name', 'comment']


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['subject', 'body']


class MailingForm(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ['title', 'start_datetime', 'periodicity', 'status', 'message', 'clients', 'is_active']


class MailingAttemptForm(forms.ModelForm):
    class Meta:
        model = MailingAttempt
        fields = '__all__'
        widgets = {
            'start_datetime': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }


class MailingAdminForm(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ['is_active']

mail_messages/views.py
import random
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from blog.models import BlogPost
from .models import Client, Message, Mailing, MailingAttempt
from .forms import ClientForm, MessageForm, MailingForm, MailingAttemptForm


@method_decorator(cache_page(60 * 5), name='dispatch')
class MainView(ListView):
    model = Mailing
    template_name = 'mail_messages/main.html'
    context_object_name = 'object_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Получение необходимой информации
        context['total_mailings'] = Mailing.objects.count()
        context['active_mailings'] = Mailing.objects.filter(is_active=True).count()
        context['unique_clients'] = Client.objects.values('email').distinct().count()

        # Получение трех случайных статей из блога
        random_articles = BlogPost.objects.all()
        context['random_articles'] = random.sample(list(random_articles),
                                                   min(len(random_articles), 3)) if random_articles.exists() else []

        return context


# ККЛИЕНТ
class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    template_name = 'mail_messages/client_list.html'
    context_object_name = 'clients'


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client
    template_name = 'mail_messages/client_detail.html'
    context_object_name = 'client'

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)

    def get_object(self):
        return get_object_or_404(Client, id=self.kwargs.get('pk'))


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    template_name = 'mail_messages/client_form.html'
    success_url = reverse_lazy('mail_messages:client_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user  # Автоматически устанавливаем владельца
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    template_name = 'mail_messages/client_form.html'
    success_url = reverse_lazy('mail_messages:client_list')

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)

    def get_object(self, queryset=None):
        message = get_object_or_404(Client, id=self.kwargs.get('pk'))

        if message.owner != self.request.user:
            raise Http404()

        return message


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    template_name = 'mail_messages/client_confirm_delete.html'
    success_url = reverse_lazy('mail_messages:client_list')

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)

    def get_object(self, queryset=None):
        message = get_object_or_404(Client, id=self.kwargs.get('pk'))

        if message.owner != self.request.user:
            raise Http404()

        return message


# СООБЩЕНИЕ
class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    template_name = 'mail_messages/message_list.html'
    context_object_name = 'messages'


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message
    template_name = 'mail_messages/message_detail.html'
    context_object_name = 'message'

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)

    def get_object(self):
        return get_object_or_404(Message, id=self.kwargs.get('pk'))


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    template_name = 'mail_messages/message_form.html'
    success_url = reverse_lazy('mail_messages:message_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    template_name = 'mail_messages/message_form.html'
    success_url = reverse_lazy('mail_messages:message_list')

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)

    def get_object(self, queryset=None):
        message = get_object_or_404(Message, id=self.kwargs.get('pk'))

        if message.owner != self.request.user:
            raise Http404()

        return message


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    template_name = 'mail_messages/message_confirm_delete.html'
    success_url = reverse_lazy('mail_messages:message_list')

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)

    def get_object(self, queryset=None):
        message = get_object_or_404(Message, id=self.kwargs.get('pk'))

        if message.owner != self.request.user:
            raise Http404()

        return message


# РАССЫЛКА
class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    template_name = 'mail_messages/mailing_list.html'
    context_object_name = 'mailings'


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing
    template_name = 'mail_messages/mailing_detail.html'
    context_object_name = 'mailing'

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)

    def get_object(self):
        return get_object_or_404(Mailing, id=self.kwargs.get('pk'))


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    template_name = 'mail_messages/mailing_form.html'
    success_url = reverse_lazy('mail_messages:mailing_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    template_name = 'mail_messages/mailing_form.html'
    success_url = reverse_lazy('mail_messages:mailing_list')
    permission_required = 'mail_messages.can_disable_mailing'

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)

    def form_valid(self, form):
        if not self.request.user.has_perm('mail_messages.can_disable_mailing'):
            return HttpResponse('У вас нет прав на отключение рассылки.', status=403)

        # Отключаем рассылку
        form.instance.is_active = False
        return super().form_valid(form)

    def get_object(self, queryset=None):
        message = get_object_or_404(Mailing, id=self.kwargs.get('pk'))

        if message.owner != self.request.user:
            raise Http404()

        return message


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    template_name = 'mail_messages/mailing_confirm_delete.html'
    success_url = reverse_lazy('mail_messages:mailing_list')

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)

    def get_object(self, queryset=None):
        message = get_object_or_404(Mailing, id=self.kwargs.get('pk'))

        if message.owner != self.request.user:
            raise Http404()

        return message


# ПОПЫТКА РАССЫЛКИ
class MailingAttemptListView(LoginRequiredMixin, ListView):
    model = MailingAttempt
    template_name = 'mail_messages/mailing_attempt_list.html'
    context_object_name = 'attempts'

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)


class MailingAttemptDetailView(LoginRequiredMixin, DetailView):
    model = MailingAttempt
    template_name = 'mail_messages/mailing_attempt_detail.html'
    context_object_name = 'attempt'

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)


class MailingAttemptCreateView(LoginRequiredMixin, CreateView):
    model = MailingAttempt
    form_class = MailingAttemptForm
    template_name = 'mail_messages/mailing_attempt_form.html'
    success_url = reverse_lazy('mail_messages:mailing_attempt_list')


class MailingAttemptUpdateView(LoginRequiredMixin, UpdateView):
    model = MailingAttempt
    form_class = MailingAttemptForm
    template_name = 'mail_messages/mailing_attempt_form.html'
    success_url = reverse_lazy('mail_messages:mailing_attempt_list')

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)


class MailingAttemptDeleteView(LoginRequiredMixin, DeleteView):
    model = MailingAttempt
    template_name = 'mail_messages/mailing_attempt_confirm_delete.html'
    success_url = reverse_lazy('mail_messages:mailing_attempt_list')

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)

mail_messages/templates/mail_messages/client_confirm_delete.html
{% extends 'mail_messages/includes/base.html' %}

{% block content %}
<body>
    <h1>Вы уверены что хотите удалить клиента "{{ client.email }}"?</h1>
    <form method="POST">
        {% csrf_token %}
        <button type="submit">Удалить</button>
    </form>
    <a href="{% url 'mail_messages:client_detail' client.id %}">Отмена</a>
</body>
{% endblock %}

mail_messages/templates/mail_messages/client_list.html
{% extends 'mail_messages/includes/base.html' %}

{% block content %}
<div class="container mt-4">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h2 class="text-center">Список клиентов</h2>
        <a href="{% url 'mail_messages:client_create' %}" class="btn btn-primary">Создать нового клиента</a>
    </div>

    <div class="list-group">
        {% for client in clients %}
            {% if client.owner == user %}
            <div class="list-group-item list-group-item-action d-flex justify-content-between align-items-center mx-auto" style="max-width: 16  00px;">
                <div>
                    <h5 class="mb-1">{{ client.name }}</h5>
                    <p class="mb-1">{{ client.email }}</p>
                    <small>{{ client.comment }}</small>
                </div>
                <div>
                    <a href="{% url 'mail_messages:client_detail' client.id %}" class="btn btn-info btn-sm">Просмотр</a>
                    <a href="{% url 'mail_messages:client_update' client.id %}" class="btn btn-sm btn-warning me-2">Редактировать</a>
                    <a href="{% url 'mail_messages:client_delete' client.id %}" class="btn btn-sm btn-danger">Удалить</a>
                </div>
            </div>
            {% endif %}
        {% empty %}
            <p class="text-center">Клиенты отсутствуют.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

mail_messages/templates/mail_messages/mailing_attempt_detail.html
{% extends 'mail_messages/includes/base.html' %}

{% block content %}
  <h1>Детали попытки рассылки</h1>
  <p><strong>ID:</strong> {{ attempt.id }}</p>
  <p><strong>Рассылка:</strong> {{ attempt.mailing }}</p>
  <p><strong>Дата и время:</strong> {{ attempt.attempt_datetime }}</p>
  <p><strong>Статус:</strong> {{ attempt.get_status_display }}</p>
  <p><strong>Ответ сервера:</strong> {{ zattempt.server_response }}</p>

  <a href="{% url 'mail_messages:mailing_attempt_update' attempt.id %}">Редактировать</a> |
  <a href="{% url 'mail_messages:mailing_attempt_list' %}">Вернуться к списку</a>
{% endblock %}

mail_messages/templates/mail_messages/mailing_attempt_form.html
{% extends 'mail_messages/includes/base.html' %}

{% block content %}
  <h1>{% if form.instance.id %}Редактировать попытку рассылки{% else %}Создать новую попытку рассылки{% endif %}</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
  </form>
  <a href="{% url 'mail_messages:mailing_attempt_list' %}">Отмена</a>
{% endblock %}

mail_messages/templates/mail_messages/mailing_attempt_list.html
{% extends 'mail_messages/includes/base.html' %}

{% block content %}
  <h1>Список попыток рассылки</h1>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Рассылка</th>
        <th>Дата и время</th>
        <th>Статус</th>
        <th>Действия</th>
      </tr>
    </thead>
    <tbody>
      {% for attempt in attempts %}
      <tr>
        <td>{{ attempt.id }}</td>
        <td>{{ attempt.mailing }}</td>
        <td>{{ attempt.attempt_datetime }}</td>
        <td>{{ attempt.status }}</td>
        <td>
          <a href="{% url 'mail_messages:mailing_attempt_detail' attempt.id %}">Детали</a> |
          <a href="{% url 'mail_messages:mailing_attempt_update' attempt.id %}">Редактировать</a> |
          <a href="{% url 'mail_messages:mailing_attempt_delete' attempt.id %}">Удалить</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <a href="{% url 'mail_messages:mailing_attempt_create' %}">Создать новую попытку</a>
{% endblock %}

mail_messages/templates/mail_messages/mailing_detail.html
{% extends 'mail_messages/includes/base.html' %}
{% load i18n %}

{% block content %}
<div class="container mt-4">
    <h2 class="text-center">{% trans "Детали рассылки" %}</h2>

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ mailing.subject }}</h5>
            <p class="card-text">{{ mailing.message.body }}</p>
            <p><strong>{% trans "Дата начала" %}:</strong> {{ mailing.start_datetime|date:"d.m.Y H:i" }}</p>
            <p><strong>{% trans "Периодичность" %}:</strong> {% trans mailing.get_periodicity_display %}</p>
            <p><strong>{% trans "Статус" %}:</strong> {% trans mailing.get_status_display %}</p>

            {% if mailing.owner == user %}
            <a href="{% url 'mail_messages:mailing_update' mailing.id %}" class="btn btn-warning">{% trans "Редактировать" %}</a>
            <a href="{% url 'mail_messages:mailing_delete' mailing.id %}" class="btn btn-danger">{% trans "Удалить" %}</a>
            <a href="{% url 'mail_messages:mailing_list' %}" class="btn btn-secondary">{% trans "Назад к списку" %}</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

mail_messages/templates/mail_messages/mailing_list.html
{% extends 'mail_messages/includes/base.html' %}

{% block content %}
<div class="container mt-4">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h2 class="text-center">Список рассылок</h2>
        <a href="{% url 'mail_messages:mailing_create' %}" class="btn btn-primary">Создать новую рассылку</a>
        <a href="{% url 'mail_messages:mailing_attempt_list' %}" class="btn btn-secondary">Попытки рассылок</a>
    </div>

    <div class="list-group">
        {% for mailing in mailings %}
        {% if mailing.owner == user %}
            <a href="{% url 'mail_messages:mailing_detail' mailing.id %}" class="list-group-item list-group-item-action">
                <h5 class="mb-1">{{ mailing.title }}</h5>
                <p class="mb-1">{{ mailing.start_datetime|date:"d.m.Y H:i" }} - {{ mailing.status }}</p>
                <small>Периодичность: {{ mailing.periodicity }}</small>
                <small>Клиенты:
                    {% for client in mailing.clients.all %}
                        {{ client.full_name }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </small>
                {% endif %}
            </a>
        {% empty %}
            <p class="text-center">Рассылки отсутствуют.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

mail_messages/templates/mail_messages/main.html
{% extends 'mail_messages/includes/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Наши Рассылки</h1>
    <p class="lead">Управляйте вашими клиентами, сообщениями и рассылками легко и эффективно.</p>
</div>

<div class="container">
    <div class="row justify-content-center mt-4">
        <div class="col-md-8">
            <div class="card shadow-lg mb-4">
                <div class="card-body text-center">
                    <h5 class="card-title">Навигация</h5>
                        <div class="d-grid gap-2">
                        <a href="{% url 'blog:blog_list' %}" class="btn btn-outline-primary btn-lg mb-3">Блог</a>
                            <p class="card-text">Выберите один из разделов для управления рассылками:</p>
                        <div class="d-grid gap-2">
                            <a href="{% url 'mail_messages:client_list' %}" class="btn btn-outline-primary btn-lg m-2">Клиенты</a>
                            <a href="{% url 'mail_messages:message_list' %}" class="btn btn-outline-success btn-lg m-2">Сообщения</a>
                            <a href="{% url 'mail_messages:mailing_list' %}" class="btn btn-outline-info btn-lg m-2">Рассылки</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-12 text-center">
            <h3 class="display-5">Случайные статьи из блога:</h3>
            <div class="row">
                {% for article in random_articles %}
                    <div class="col-md-4 mb-4">
                        <div class="card">
                            <img src="{{ article.image.url }}" class="card-img-top" alt="{{ article.title }}" style="height: 200px; object-fit: cover;">
                            <div class="card-body d-flex flex-column">
                                <h5 class="card-title">{{ article.title }}</h5>
                                <a href="{% url 'blog:blog_detail' article.pk %}" class="btn btn-primary mt-auto">Читать далее</a>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <div class="alert alert-warning">Нет доступных статей.</div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="row text-center mt-4">
        <div class="col-md-4">
            <h6>Количество рассылок всего:</h6>
            <p class="display-4 fw-normal">{{ total_mailings }}</p>
        </div>
        <div class="col-md-4">
            <h6>Количество активных рассылок:</h6>
            <p class="display-4 fw-normal">{{ active_mailings }}</p>
        </div>
        <div class="col-md-4">
            <h6>Количество уникальных клиентов:</h6>
            <p class="display-4 fw-normal">{{ unique_clients }}</p>
        </div>
    </div>
</div>
{% endblock %}

mail_messages/templates/mail_messages/message_detail.html
{% extends 'mail_messages/includes/base.html' %}

{% block content %}
    <div class="container">
        <h2>Сообщение</h2>
        <div class="card">
            <div class="card-header">
                <h2>{{ message.subject }}</h2>
            </div>
            <div class="card-body">
                <p>{{ message.body }}</p>
            </div>
            <div class="card-footer">
                {% if message.owner == user %}
                <a href="{% url 'mail_messages:message_update' message.id %}" class="btn btn-warning">Редактировать</a>
                <a href="{% url 'mail_messages:message_list' %}" class="btn btn-secondary">Вернуться к списку</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

mail_messages/templates/mail_messages/message_list.html
{% extends 'mail_messages/includes/base.html' %}

{% block content %}
    <div class="container mt-4">
        <div class="d-flex justify-content-between align-items-center mb-4">
            <h2 class="text-center">Список сообщений</h2>
            <a href="{% url 'mail_messages:message_create' %}" class="btn btn-primary">Создать сообщение</a>
        </div>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Тема</th>
                    <th>Текст сообщения</th>
                    <th>Действия</th>
                </tr>
            </thead>
            <tbody>
                {% for message in messages %}
                {% if message.owner == user %}
                <tr>
                    <td>{{ message.subject }}</td>
                    <td>{{ message.body|truncatewords:10 }}</td>
                    <td>
                        <a href="{% url 'mail_messages:message_detail' message.id %}" class="btn btn-info btn-sm">Просмотр</a>
                        <a href="{% url 'mail_messages:message_update' message.id %}" class="btn btn-warning btn-sm">Редактировать</a>
                        <a href="{% url 'mail_messages:message_delete' message.id %}" class="btn btn-danger btn-sm">Удалить</a>
                        {% endif %}
                    </td>
                    {% endfor %}
                </tr>
                <tr>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}