blog/urls.py
from django.urls import path

from blog.views import BlogListView, BlogDetailView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from blog import urls
import blog
from users import urls
import users
from mail_messages import urls
import mail_messages

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(mail_messages.urls, namespace='mail_messages')),
    path('users/', include(users.urls, namespace='users')),
    path('blog/', include(blog.urls, namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mail_messages/urls.py
from django.urls import path
from .views import (
    ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView,
    MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView,
    MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView,
    MailingAttemptListView, MailingAttemptDetailView, MailingAttemptCreateView, MailingAttemptUpdateView,
    MailingAttemptDeleteView, MainView,
)

app_name = "mail_messages"

urlpatterns = [
    path('', (MainView.as_view()), name='main'),

    # КЛИЕНТ
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('clients/create/', ClientCreateView.as_view(), name='client_create'),
    path('clients/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('clients/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),

    # СООБЩЕНИЕ
    path('messages/', MessageListView.as_view(), name='message_list'),
    path('messages/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('messages/create/', MessageCreateView.as_view(), name='message_create'),
    path('messages/<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('messages/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),

    # РАССЫЛКА
    path('mailing/', MailingListView.as_view(), name='mailing_list'),
    path('mailing/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing/<int:pk>/update/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),

    # ПОПЫТКА РАССЫЛКИ
    path('mailing-attempt/', MailingAttemptListView.as_view(), name='mailing_attempt_list'),
    path('mailing-attempt/<int:pk>/', MailingAttemptDetailView.as_view(), name='mailing_attempt_detail'),
    path('mailing-attempt/create/', MailingAttemptCreateView.as_view(), name='mailing_attempt_create'),
    path('mailing-attempt/<int:pk>/update/', MailingAttemptUpdateView.as_view(), name='mailing_attempt_update'),
    path('mailing-attempt/<int:pk>/delete/', MailingAttemptDeleteView.as_view(), name='mailing_attempt_delete'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.views import RegisterView, ProfileView, activate, BlockUserView

app_name = 'users'

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('activate/<uidb64>/<token>/', activate, name='verify_email'),
    path('users/<int:pk>/block/', BlockUserView.as_view(), name='block_user'),
]

mail_messages/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


# Клиент
class Client(models.Model):
    email = models.EmailField(unique=True, verbose_name='почта')
    full_name = models.CharField(max_length=255, verbose_name='ФИО')
    comment = models.TextField(**NULLABLE, verbose_name='комментарий')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE,
                              verbose_name='владелец',
                              related_name='clients'
                              )

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


# Сообщение
class Message(models.Model):
    subject = models.CharField(max_length=255, verbose_name='тема письма')
    body = models.TextField(verbose_name='тело письма')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE,
                              verbose_name='владелец',
                              related_name='messages'
                              )

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'соббщение'
        verbose_name_plural = 'сообщения'


# Рассылка
class Mailing(models.Model):
    PERIODICITY_CHOICES = [
        ('daily', 'Раз в день'),
        ('weekly', 'Раз в неделю'),
        ('monthly', 'Раз в месяц'),
    ]

    STATUS_CHOICES = [
        ('created', 'Создана'),
        ('started', 'Запущена'),
        ('completed', 'Завершена'),
    ]

    title = models.CharField(max_length=100, default='Без названия', verbose_name='Название рассылки')
    start_datetime = models.DateTimeField(verbose_name='Дата и время первой рассылки')
    periodicity = models.CharField(max_length=10, choices=PERIODICITY_CHOICES, verbose_name='Периодичность рассылки')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='created', verbose_name='Статус рассылки')
    message = models.OneToOneField(Message, on_delete=models.CASCADE, verbose_name='Сообщение')
    clients = models.ManyToManyField(Client, verbose_name='Клиенты')
    is_active = models.BooleanField(default=True, verbose_name='активность рассылки')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE,
                              verbose_name='владелец',
                              related_name='mailings'
                              )

    def __str__(self):
        return f"{self.title} (ID: {self.id}) - {self.status}"

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

        permissions = [
            ("can_disable_mailing", "Can disable mailing"),
        ]


# Попытка рассылки
class MailingAttempt(models.Model):
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='рассылка')
    attempt_datetime = models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней рассылки')
    status = models.CharField(max_length=10, choices=[('success', 'Успешно'), ('failed', 'Неуспешно')], verbose_name='статус попытки')
    server_response = models.TextField(verbose_name='ответ почтового сервиса', **NULLABLE)

    def __str__(self):
        return f"Attempt for mailing {self.mailing.id} - {self.status}"

    class Meta:
        verbose_name = 'попытка рассылки'
        verbose_name_plural = 'попытки рассылки'

mail_messages/forms.py
from django import forms
from .models import Client, Message, Mailing, MailingAttempt


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['email', 'full_name', 'comment']


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['subject', 'body']


class MailingForm(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ['title', 'start_datetime', 'periodicity', 'status', 'message', 'clients', 'is_active']


class MailingAttemptForm(forms.ModelForm):
    class Meta:
        model = MailingAttempt
        fields = '__all__'
        widgets = {
            'start_datetime': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }


class MailingAdminForm(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ['is_active']

mail_messages/views.py
import random
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from blog.models import BlogPost
from .models import Client, Message, Mailing, MailingAttempt
from .forms import ClientForm, MessageForm, MailingForm, MailingAttemptForm


@method_decorator(cache_page(60 * 5), name='dispatch')
class MainView(ListView):
    model = Mailing
    template_name = 'mail_messages/main.html'
    context_object_name = 'object_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Получение необходимой информации
        context['total_mailings'] = Mailing.objects.count()
        context['active_mailings'] = Mailing.objects.filter(is_active=True).count()
        context['unique_clients'] = Client.objects.values('email').distinct().count()

        # Получение трех случайных статей из блога
        random_articles = BlogPost.objects.all()
        context['random_articles'] = random.sample(list(random_articles),
                                                   min(len(random_articles), 3)) if random_articles.exists() else []

        return context


# ККЛИЕНТ
class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    template_name = 'mail_messages/client_list.html'
    context_object_name = 'clients'


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client
    template_name = 'mail_messages/client_detail.html'
    context_object_name = 'client'

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)

    def get_object(self):
        return get_object_or_404(Client, id=self.kwargs.get('pk'))


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    template_name = 'mail_messages/client_form.html'
    success_url = reverse_lazy('mail_messages:client_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user  # Автоматически устанавливаем владельца
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    template_name = 'mail_messages/client_form.html'
    success_url = reverse_lazy('mail_messages:client_list')

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)

    def get_object(self, queryset=None):
        message = get_object_or_404(Client, id=self.kwargs.get('pk'))

        if message.owner != self.request.user:
            raise Http404()

        return message


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    template_name = 'mail_messages/client_confirm_delete.html'
    success_url = reverse_lazy('mail_messages:client_list')

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)

    def get_object(self, queryset=None):
        message = get_object_or_404(Client, id=self.kwargs.get('pk'))

        if message.owner != self.request.user:
            raise Http404()

        return message


# СООБЩЕНИЕ
class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    template_name = 'mail_messages/message_list.html'
    context_object_name = 'messages'


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message
    template_name = 'mail_messages/message_detail.html'
    context_object_name = 'message'

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)

    def get_object(self):
        return get_object_or_404(Message, id=self.kwargs.get('pk'))


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    template_name = 'mail_messages/message_form.html'
    success_url = reverse_lazy('mail_messages:message_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    template_name = 'mail_messages/message_form.html'
    success_url = reverse_lazy('mail_messages:message_list')

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)

    def get_object(self, queryset=None):
        message = get_object_or_404(Message, id=self.kwargs.get('pk'))

        if message.owner != self.request.user:
            raise Http404()

        return message


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    template_name = 'mail_messages/message_confirm_delete.html'
    success_url = reverse_lazy('mail_messages:message_list')

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)

    def get_object(self, queryset=None):
        message = get_object_or_404(Message, id=self.kwargs.get('pk'))

        if message.owner != self.request.user:
            raise Http404()

        return message


# РАССЫЛКА
class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    template_name = 'mail_messages/mailing_list.html'
    context_object_name = 'mailings'


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing
    template_name = 'mail_messages/mailing_detail.html'
    context_object_name = 'mailing'

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)

    def get_object(self):
        return get_object_or_404(Mailing, id=self.kwargs.get('pk'))


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    template_name = 'mail_messages/mailing_form.html'
    success_url = reverse_lazy('mail_messages:mailing_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    template_name = 'mail_messages/mailing_form.html'
    success_url = reverse_lazy('mail_messages:mailing_list')
    permission_required = 'mail_messages.can_disable_mailing'

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)

    def form_valid(self, form):
        if not self.request.user.has_perm('mail_messages.can_disable_mailing'):
            return HttpResponse('У вас нет прав на отключение рассылки.', status=403)

        # Отключаем рассылку
        form.instance.is_active = False
        return super().form_valid(form)

    def get_object(self, queryset=None):
        message = get_object_or_404(Mailing, id=self.kwargs.get('pk'))

        if message.owner != self.request.user:
            raise Http404()

        return message


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    template_name = 'mail_messages/mailing_confirm_delete.html'
    success_url = reverse_lazy('mail_messages:mailing_list')

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)

    def get_object(self, queryset=None):
        message = get_object_or_404(Mailing, id=self.kwargs.get('pk'))

        if message.owner != self.request.user:
            raise Http404()

        return message


# ПОПЫТКА РАССЫЛКИ
class MailingAttemptListView(LoginRequiredMixin, ListView):
    model = MailingAttempt
    template_name = 'mail_messages/mailing_attempt_list.html'
    context_object_name = 'attempts'

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)


class MailingAttemptDetailView(LoginRequiredMixin, DetailView):
    model = MailingAttempt
    template_name = 'mail_messages/mailing_attempt_detail.html'
    context_object_name = 'attempt'

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)


class MailingAttemptCreateView(LoginRequiredMixin, CreateView):
    model = MailingAttempt
    form_class = MailingAttemptForm
    template_name = 'mail_messages/mailing_attempt_form.html'
    success_url = reverse_lazy('mail_messages:mailing_attempt_list')


class MailingAttemptUpdateView(LoginRequiredMixin, UpdateView):
    model = MailingAttempt
    form_class = MailingAttemptForm
    template_name = 'mail_messages/mailing_attempt_form.html'
    success_url = reverse_lazy('mail_messages:mailing_attempt_list')

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)


class MailingAttemptDeleteView(LoginRequiredMixin, DeleteView):
    model = MailingAttempt
    template_name = 'mail_messages/mailing_attempt_confirm_delete.html'
    success_url = reverse_lazy('mail_messages:mailing_attempt_list')

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)

mail_messages/templates/mail_messages/includes/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Sixtyfour+Convergence&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Allura&display=swap" rel="stylesheet">
    <meta name="theme-color" content="#7952b3">

    <style>
        h4 {
            font-family: 'Sixtyfour Convergence', cursive;
            font-size: 4rem;
        }
        h3 {
            font-family: 'Allura', cursive;
            font-size: 2rem;
        }
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
</head>
<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">RASSILKI<3</h4>
                    <p class="text-muted mb-4 fs-5">
                        <span class="font-weight-bold"></span>
                        <span class="text-primary">HELLO SKYPRO</span>
                        <span class="text-primary"></span>
                        <span class="text-primary"></span>
                    </p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Меню</h4>
                    <ul class="list-unstyled">
                        {% if user.is_authenticated %}
                           <li><a href="{% url 'users:profile' %}" class="btn btn-outline-secondary">ПРОФИЛЬ</a></li>
                           <li>
                              <form method="POST" action="{% url 'users:logout' %}">
                                 {% csrf_token %}
                                 <button type="submit" class="btn btn-outline-secondary">ВЫЙТИ</button>
                              </form>
                           </li>
                        {% else %}
                           <li><a href="{% url 'users:login' %}" class="btn btn-outline-secondary">ВОЙТИ</a></li>
                           <li><a href="{% url 'users:register' %}" class="btn btn-outline-secondary">РЕГИСТРАЦИЯ</a></li>
                        {% endif %}
                        <li><a href="#" class="text-white">На главную</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="{% url 'mail_messages:main' %}" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
                <strong>НашиРассылки</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">{{ title }}</h1>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</main>

{% include 'mail_messages/includes/inc_downstr.html' with object=object %}

<script src="{% static 'js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>

</body>
</html>

mail_messages/templates/mail_messages/includes/inc_downstr.html
<footer class="text-muted py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
        <h3 class="mb-1">&copy; НашиРассылки<3</h3>
        <p class="mb-0">
    </div>
</footer>